### ISSUE TITLE
Scrollable content cannot dismiss

### ISSUE THREAD

**Issue by Sovai** [radix-vue/vaul-vue#36]
The drawer with scrollable content cannot be dismissed. pls see the code below

``` vue
<template>
  <DrawerRoot should-scale-background>
    <DrawerTrigger
      class="rounded-full bg-white px-4 py-2.5 text-sm font-semibold text-app-positive shadow-sm ring-1 ring-inset ring-app-positive hover:bg-app-positive"
    >
      Open Drawer
    </DrawerTrigger>
    <DrawerPortal>
      <DrawerOverlay class="fixed bg-dark-primary/50 inset-0" />
      <DrawerContent
        class="bg-light-primary flex flex-col fixed bottom-0 left-0 right-0 max-h-[96%] rounded-t-[10px]"
      >
        <div
          class="max-w-md w-full mx-auto flex flex-col overflow-auto p-4 rounded-t-[10px]"
        >
          <input class="border border-gray-400 my-8" placeholder="Input" />
          <p>
            But I must explain to you how all this mistaken idea of denouncing
            pleasure and praising pain was born and I will give you a complete
            account of the system, and expound the actual teachings of the great
            explorer of the truth, the master-builder of human happiness. No one
            rejects, dislikes, or avoids pleasure itself, because it is
            pleasure, but because those who do not know how to pursue pleasure
            rationally encounter consequences that are extremely painful. Nor
            again is there anyone who loves or pursues or desires to obtain pain
            of itself, because it is pain, but because occasionally
            circumstances occur in which toil and pain can procure him some
            great pleasure. To take a trivial example, which of us ever
            undertakes laborious physical exercise, except to obtain some
            advantage from it? But who has any right to find fault with a man
            who chooses to enjoy a pleasure that has no annoying consequences,
            or one who avoids a pain that produces no resultant pleasure?
          </p>
          <input class="border border-gray-400 my-8" placeholder="Input" />
          <p>
            On the other hand, we denounce with righteous indignation and
            dislike men who are so beguiled and demoralized by the charms of
            pleasure of the moment, so blinded by desire, that they cannot
            foresee the pain and trouble that are bound to ensue; and equal
            blame belongs to those who fail in their duty through weakness of
            will, which is the same as saying through shrinking from toil and
            pain. These cases are perfectly simple and easy to distinguish. In a
            free hour, when our power of choice is untrammelled and when nothing
            prevents our being able to do what we like best, every pleasure is
            to be welcomed and every pain avoided. But in certain circumstances
            and owing to the claims of duty or the obligations of business it
            will frequently occur that pleasures have to be repudiated and
            annoyances accepted. The wise man therefore always holds in these
            matters to this principle of selection: he rejects pleasures to
            secure other greater pleasures, or else he endures pains to avoid
            worse pains.
          </p>
          <input class="border border-gray-400 my-8" placeholder="Input" />
        </div>
      </DrawerContent>
    </DrawerPortal>
  </DrawerRoot>
</template>
<script setup>
import {
  DrawerContent,
  DrawerOverlay,
  DrawerPortal,
  DrawerRoot,
  DrawerTrigger,
} from "vaul-vue";


</script>
```

**Comment by zaosoula** [comment]
+1

**Comment by hiclosecom** [comment]
+1

**Comment by zernonia** [comment]
Upstream issue https://github.com/emilkowalski/vaul/issues/281

**Comment by genius192x** [comment]
@zernonia hi, maybe this is solution https://github.com/emilkowalski/vaul/issues/281#issuecomment-2301503046  it is not the best one, but at least prevent strange things

**Comment by anbraten** [comment]
From a short check those lines from the upstream code: https://github.com/emilkowalski/vaul/blob/main/src/index.tsx#L577-L600

seem to be missing:

https://github.com/radix-vue/vaul-vue/blob/main/packages/vaul-vue/src/controls.ts#L544-L560

**Comment by mary-ext** [comment]
Is this actually an upstream issue? Vaul's docs has an example on scrollable content and it seems to be fine (Android 14; Chrome 130)

Not sure if their docs has an up-to-date version of the library or not.

**Comment by SiiLuu** [comment]
Hi any news with this bug ?

**Comment by nextifier** [comment]
Has anyone come up with a solution? The problem occurs only when we have "overflow-*" to the DrawerContent or its children, and happens only on touch devices. In original Shadcn UI website, they use Drawer for the menu with scrollable content, and that works fine.

**Comment by paro-paro** [comment]
Is this issue addressed in the latest release?

**Comment by mforstme** [comment]
+1

**Comment by brolnickij** [comment]
+1

**Comment by MickL** [comment]
Guys instead of spamming useless +1 you should upvote the issue, or may open a PR, but this adds nothing except for spam.

Anyway, this issue makes vaul-vue kinda useless. My drawer comes from the side and has scrollable content. With scrollable content either the content cant be scrolled if `overflow-y-auto` is added to `DrawerContent` OR the content can be scrolled but drawer cant be closed.

`overflow-y: auto` on `DrawerContent`:
https://github.com/user-attachments/assets/7963cb21-0ffd-4eb6-a171-a19da95feb52

`overflow-y: auto` on child:
https://github.com/user-attachments/assets/24fc201b-6d1c-4639-bfde-9ace8b5962d8

**Comment by MickL** [comment]
Hey @harkor @zernonia thanks for the PR! However, doesnt this just set the default of `allowedToDrag` to ?`false` or am I overseeing something?

- I think in my example (drawer comes from the side) the drawer should be draggable horizontally, but scrollable vertically
- In the other case (drawer comes from bottom), the drawer could be closable if content is scrolled all the way up, otherwise not react.

**Comment by mary-ext** [comment]
I'm not sure if the PR solves it? here's a StackBlitz example I've built to demonstrate this
https://stackblitz.com/edit/vitejs-vite-1xdy1r4h?file=src%2FApp.vue

**Comment by nextifier** [comment]
I don't think this issue is fixed.

https://ui.shadcn.com/
https://www.shadcn-vue.com/

Just open the original shadcn website and shadcn-vue website in mobile version. Open the menu. Both of them use Drawer to display menu in mobile version.

But the shadcn-vue version has 2 problems:
1. It will not close the Drawer when swiped to bottom if the DrawerContent has overflow. 
2. When scrollable DrawerContent is scrolled up or down, the Drawer height keep changing.

The original shadcn menu drawer doesn't have those 2 issues.

(I found a hacky trick to fix the problem 1 by adding scroll listener to the DrawerContent that check if the drawer content position is at the top or not, if at the top, then apply class "touch-pan-down" so it can only swiped up, but swiped bottom will not scroll the content.)

`<script lang="ts" setup>
import { DrawerContent, DrawerPortal } from "vaul-vue";
import type { DialogContentEmits, DialogContentProps } from "radix-vue";
import { useForwardPropsEmits } from "radix-vue";
import type { HtmlHTMLAttributes } from "vue";
import DrawerOverlay from "./DrawerOverlay.vue";
import { cn } from "@/lib/utils";

const props = defineProps({
  class: { type: String, required: false },
  overflowContent: { type: Boolean, default: true },
});

const emits = defineEmits<DialogContentEmits>();

const forwarded = useForwardPropsEmits(props, emits);

const drawerContentBody = ref(null);
const yPosition = ref(0);
const isAtTop = ref(true);

const handleScroll = () => {
  if (drawerContentBody.value) {
    yPosition.value = drawerContentBody.value.scrollTop;
    isAtTop.value = yPosition.value === 0;
  }
};
</script>

<template>
  <DrawerPortal>
    <DrawerOverlay />
    <DrawerContent
      v-bind="forwarded"
      :class="
        cn(
          'fixed inset-x-0 bottom-0 z-50 mt-24 flex h-auto max-h-[80vh] flex-col rounded-t-2xl border-t bg-white outline-none dark:bg-gray-950 lg:max-h-[calc(100lvh-var(--navbar-height-desktop))]',
          props.class,
        )
      "
    >
      <div
        class="mx-auto mb-4 mt-2 h-2 w-[100px] flex-shrink-0 rounded-full bg-gray-200 dark:bg-gray-800"
      />

      <div
        ref="drawerContentBody"
        class="pointer-events-auto"
        :class="{
          'touch-pan-down': isAtTop,
          'overflow-y-auto': props.overflowContent,
        }"
        @scroll="handleScroll"
      >
        <slot />
      </div>
    </DrawerContent>
  </DrawerPortal>
</template>`

**Comment by MickL** [comment]
Can this be reopened please? @zernonia

**Comment by MickL** [comment]
@zernonia Can you please reopen? This issue still persists, scrollable content cant be closed on touch devices. This also affects Reka UI and Nuxt UI.

**Comment by alexwohlbruck** [comment]
I've been fiddling with this for a few days and have a decent solution for a non-modal bottom drawer, similar to what you get in google maps with scrollable content and horizontal scrolling child containers.

https://github.com/user-attachments/assets/d6d9efa4-8150-4185-ba11-8404bb2adc14

1. We create a vertically scrollable container inside the drawer with some conditional css:

```html
<DrawerContent
  class="bg-gray-100 flex flex-col rounded-t-[10px] h-full fixed bottom-0 left-0 right-0 border-t"
>
  <div
    ref="scrollContainer"
    class="p-4 bg-white rounded-t-[10px] flex-1"
    :class="{ 'overflow-y-auto': isFullyExpanded }"
    :style="{ touchAction: isFullyExpanded ? 'pan-y' : 'none' }"
    @touchstart="handleTouchStart"
    @touchmove="handleTouchMove"
    @touchend="handleTouchEnd"
    >
    Drawer content...
  </div>
</DrawerContent>
```

We need to define some values:
```typescript
const snapPoints = ref(['180px', 0.5, 1])
const scrollContainer = ref<HTMLElement | null>(null)
const activeSnapPoint = ref<number | string | null>(null)

let lastTouchY = 0
let isScrollingUp = false
const { y: scrollY } = useScroll(scrollContainer)
const isAtTop = computed(() => scrollY.value === 0)
const isFullyExpanded = computed(() => activeSnapPoint.value === 1)

function snapPointChanged(snapPoint: number | string | null) {
  activeSnapPoint.value = snapPoint
}
```

We use these touch event handlers to disable scroll when the container scrolled to top, drawer is fully expanded, and user swipes down
```typescript
function handleTouchStart(e: TouchEvent) {
  lastTouchY = e.touches[0].clientY
}

function handleTouchMove(e: TouchEvent) {
  if (!isFullyExpanded.value) return
  
  const currentTouchY = e.touches[0].clientY
  const deltaY = currentTouchY - lastTouchY
  isScrollingUp = deltaY > 0 // Positive deltaY means scrolling up (finger moving down)
  
  // Prevent upward scroll when at the top of the container
  if (isAtTop.value && isScrollingUp) {
    e.preventDefault()
    return false
  }
  
  lastTouchY = currentTouchY
}

function handleTouchEnd() {
  isScrollingUp = false
}
```

2. For any child containers that have horizontal scrollable content, we run into the same bug. For these, we will disable vertical pan with a simple css fix `touch-action: pan-x;`:

```html
<div class="overflow-x-auto -mx-4 px-4 mb-8 touch-pan-x">
  <div class="flex gap-4">
    <div class="w-[200px] h-[150px] flex-shrink-0 bg-gray-300 rounded-lg"></div>
    <div class="w-[200px] h-[150px] flex-shrink-0 bg-gray-300 rounded-lg"></div>
    <div class="w-[200px] h-[150px] flex-shrink-0 bg-gray-300 rounded-lg"></div>
    <div class="w-[200px] h-[150px] flex-shrink-0 bg-gray-300 rounded-lg"></div>
    <div class="w-[200px] h-[150px] flex-shrink-0 bg-gray-300 rounded-lg"></div>
  </div>
</div>
```

3. We also apply the fix for the opening animation from https://github.com/unovue/vaul-vue/issues/108:

```vue
<style scoped>
[data-vaul-drawer] {
  position: fixed;
}

[data-vaul-drawer][data-vaul-snap-points=true][data-vaul-drawer-direction=bottom][data-state=open] {
  animation-name: slideFromBottomToSnapPoint;
}

@keyframes slideFromBottomToSnapPoint {
  from {
    transform: translate3d(0, var(--initial-transform, 100%), 0);
  }
  to {
    transform: translate3d(0, var(--snap-point-height, 0), 0);
  }
}
</style>
```

Full code solution using the playground example in the repo:

```vue
<script setup lang="ts">
import { computed, ref } from 'vue';
import { useScroll } from '@vueuse/core'
import { DrawerContent, DrawerHandle, DrawerOverlay, DrawerPortal, DrawerRoot, DrawerTrigger } from 'vaul-vue'

const snapPoints = ref(['180px', 0.5, 1])
const scrollContainer = ref<HTMLElement | null>(null)
const activeSnapPoint = ref<number | string | null>(null)

let lastTouchY = 0
let isScrollingUp = false
const { y: scrollY } = useScroll(scrollContainer)
const isAtTop = computed(() => scrollY.value === 0)
const isFullyExpanded = computed(() => activeSnapPoint.value === 1)

function snapPointChanged(snapPoint: number | string | null) {
  activeSnapPoint.value = snapPoint
}

function handleTouchStart(e: TouchEvent) {
  lastTouchY = e.touches[0].clientY
}

function handleTouchMove(e: TouchEvent) {
  if (!isFullyExpanded.value) return
  
  const currentTouchY = e.touches[0].clientY
  const deltaY = currentTouchY - lastTouchY
  isScrollingUp = deltaY > 0 // Positive deltaY means scrolling up (finger moving down)
  
  // Prevent upward scroll when at the top of the container
  if (isAtTop.value && isScrollingUp) {
    e.preventDefault()
    return false
  }
  
  lastTouchY = currentTouchY
}

function handleTouchEnd() {
  isScrollingUp = false
}
</script>

<template>
  <DrawerRoot
    direction="bottom"
    :snap-points="snapPoints"
    v-model:active-snap-point="activeSnapPoint"
    @update:activeSnapPoint="snapPointChanged"
    :modal="false"
    :repositionInputs="true"
    >
    <DrawerTrigger
      class="rounded-full bg-white px-4 py-2.5 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50"
    >
      Open Drawer
    </DrawerTrigger>
    <DrawerPortal>
      <DrawerOverlay class="fixed bg-black/40 inset-0" />
      <DrawerContent
        class="bg-gray-100 flex flex-col rounded-t-[10px] h-full fixed bottom-0 left-0 right-0 border-t"
      >
        <div
          ref="scrollContainer"
          class="p-4 bg-white rounded-t-[10px] flex-1"
          :class="{ 'overflow-y-auto': isFullyExpanded }"
          :style="{ touchAction: isFullyExpanded ? 'pan-y' : 'none' }"
          @touchstart="handleTouchStart"
          @touchmove="handleTouchMove"
          @touchend="handleTouchEnd"
          >

          <div class="max-w-md mx-auto">
            <h2 id="radix-:R3emdaH1:" class="font-medium mb-4">
              Drawer for Vue.
            </h2>

            <div class="overflow-x-auto -mx-4 px-4 mb-8 touch-pan-x">
              <div class="flex gap-4">
                <div class="w-[200px] h-[150px] flex-shrink-0 bg-gray-300 rounded-lg"></div>
                <div class="w-[200px] h-[150px] flex-shrink-0 bg-gray-300 rounded-lg"></div>
                <div class="w-[200px] h-[150px] flex-shrink-0 bg-gray-300 rounded-lg"></div>
                <div class="w-[200px] h-[150px] flex-shrink-0 bg-gray-300 rounded-lg"></div>
                <div class="w-[200px] h-[150px] flex-shrink-0 bg-gray-300 rounded-lg"></div>
              </div>
            </div>

            <p v-for="i in 100" :key="i">
              test {{ i }}
            </p>
          </div>
        </div>
      </DrawerContent>
    </DrawerPortal>
  </DrawerRoot>
</template>

<style scoped>
[data-vaul-drawer] {
  position: fixed;
}

[data-vaul-drawer][data-vaul-snap-points=true][data-vaul-drawer-direction=bottom][data-state=open] {
  animation-name: slideFromBottomToSnapPoint;
}

@keyframes slideFromBottomToSnapPoint {
  from {
    transform: translate3d(0, var(--initial-transform, 100%), 0);
  }
  to {
    transform: translate3d(0, var(--snap-point-height, 0), 0);
  }
}
</style>
```

**Comment by luizotcarvalho** [comment]
Looks like porting vaul's `use-prevent-scroll.ts` did the job, I've tested with scrollable content and swipe down dismiss.

https://github.com/unovue/vaul-vue/pull/114

**Comment by mehedimi** [comment]
I’m using the `Shadcn Vue Drawer` component and ran into a scrolling issue. After investigating, I found that under the hood it relies on the `unovue/vaul-vue` package.

To fix the problem, I modified the `DrawerContent.vue` component by wrapping the slot content in an additional div with `overflow-y-auto`. This fix issue temporary for me.

```html
<div class="overflow-y-auto">
    <slot />
</div>
```
